version: 2

models:
  - name: int_users
    description: "Puhastatud kasutajaandmed staging kihist"
    columns:
      - name: uuid
        tests:
          - unique
          - not_null
      - name: email
        tests:
          - not_null
      - name: user_id
        tests:
          - unique
          - not_null

  - name: int_posts
    description: "Puhastatud postitused staging kihist"
    columns:
      - name: post_id
        tests:
          - unique
          - not_null
      - name: user_id
        tests:
          - not_null
